### ISSUE TITLE
Out-of-date requirements file

### ISSUE THREAD

**Issue by mishagin-tim** [microsoft/python-sample-tweeterapp#12]
Hello! 

You have an out-of-date requirements file. 

### psycopg-2.7.4 is not compatible with python 3.8.*

> If you leave it unchanged and try to run a remote docker folder, you will get this issue (because of old version of psycopg2 which is not compatible with python 3.8.*).
> 
> [errorlog.txt](https://github.com/microsoft/python-sample-tweeterapp/files/4779269/errorlog.txt)
> 
> It also was discussed in this thread:
> https://github.com/psycopg/psycopg2/issues/854#issuecomment-636526605
> 
> **You can simply fix it by replacing the version of psycopg2 in requirements file with the last stable version of psycopg from psycopg.com (2.8.5 for instance)**
> 
> Replace this
> 
> `psycopg2==2.7.4 --no-binary psycopg2`
> 
> with this
> 
> `psycopg2==2.8.5 --no-binary psycopg2`

### djangorestframework-3.9.1 is not compatible with django 3.*
> It won't let you to migrate your models, if you don't update. Because of deprecated django.utils.six module.
>
> **Solution**:
> `pip install djangorestframework --upgrade` 

### whitenoise-4.1 is not compatible with django 3.*
> Same as above. Now it won't let you run server. Again this six import!!
>
> **Solution**:
> `pip install whitenoise --upgrade`

**Comment by luabud** [comment]
Thanks @mishagin-tim for bringing it up! I updated the packages, it's working for me but it'd be great if others could confirm 😊
